version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: elearning_mysql
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: elearning
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - elearning_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  web:
    build: .
    container_name: elearning_web
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=elearning
    volumes:
      - ./uploads:/app/uploads
      - ./static:/app/static
      - ./main.py:/app/main.py
      - ./requirements.txt:/app/requirements.txt
    networks:
      - elearning_network

volumes:
  mysql_data:

networks:
  elearning_network:
    driver: bridge
